spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sideralti
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: 123
      # roles: ADMIN
