spring:
  profiles:
    active: dev

server:
  port: 9000
  servlet:
    context-path: /sideralti/api/v1

application:
  developer: Sideralti
  title: Diente Blanco Dental Clinic
  description: Sideralti API Documentation
  version:  -->  v1.0.0

springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
